# Generated by Django 4.2.6 on 2023-10-16 02:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, verbose_name='ニックネーム')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(18, '18歳未満は登録できません'), django.core.validators.MaxValueValidator(100, '100歳を超えて登録はできません')], verbose_name='年齢')),
                ('sex', models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=16, verbose_name='性別')),
                ('introduction', models.TextField(max_length=1000, verbose_name='自己紹介')),
                ('favorite_book_category', models.TextField(max_length=100, verbose_name='好きな本のカテゴリ')),
                ('like_book', models.TextField(max_length=256, verbose_name='好きな本')),
                ('favorite_author', models.TextField(max_length=1000, verbose_name='好きな作家')),
                ('create_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, verbose_name='メッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='Matching.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Matching.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False, verbose_name='マッチング許可')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('approached', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approached', to='Matching.profile')),
                ('approaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approaching', to='Matching.profile')),
            ],
            options={
                'unique_together': {('approaching', 'approached')},
            },
        ),
    ]
